services:
  app:
    build: .
    container_name: backend-coffee-app
    environment:
      DATABASE_URL: postgresql://postgres:password@postgres:5432/coffee
      JWT_SECRET: 'backend'
    ports:
      - '3003:3000'
    depends_on:
      postgres:
        condition: service_healthy
    command: >
      sh -c "npx prisma db push && npx prisma db seed && npm run start:prod"

  postgres:
    container_name: postgres-coffee-app
    image: postgres:17-alpine3.21
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: coffee
    ports:
      - '5440:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
